### ISSUE TITLE
Linux Output Messages MalConfigured

### ISSUE THREAD

**Issue by HeIp** [peterpt/IPTV-CHECK#1]
![image](https://user-images.githubusercontent.com/31706214/39482240-48c159ce-4d3c-11e8-8b1f-85d419ae38fa.png)

**Comment by peterpt** [comment]
where are you running the script , witch OS and witch architecture ?
From what i see , that is an issue with your terminal emulator and not the script itself .

**Comment by HeIp** [comment]
it's MacOS Terminal

**Comment by peterpt** [comment]
The script was build to run in a normal linux environment and was not build to run in MacOS .
Is is almost the same thing as an user asking support to microsoft ro run a linux script n Windows .
Microsoft just dont even reply to that question or support because the OS work differently .
However , Mac also have some of the tools that linux have , like the basic tools , and this is why the script is working in your image , but those numbers are the color codes witch since you are using a MAC terminal and not gnome , xterm or any other base linux terminal , they dont display the colours because your terminal do not understand the code .

There is nothing to fix here in the script , create a Virtual Machine with linux in it and run the script there and your problem will be solved .
