### ISSUE TITLE
Compatibility for WSL

### ISSUE THREAD

**Issue by rrjanbiah** [peterpt/IPTV-CHECK#9]
In WSL, it doesn't work due to path issues. The global install option doesn't look necessary as otherwise, it could work smoothly.

**Comment by rrjanbiah** [comment]
Issues in WSL:

![image](https://github.com/peterpt/IPTV-CHECK/assets/4907427/00b9b85d-4f3b-4f50-8791-c1736b250964)

**Comment by peterpt** [comment]
iptv-check was not build to work on an linux sub sistem in windows , the reason is that the tool requires its own installation path to work with temporary files while working . some commands are send to null to avoid possible errors, mostly on removing files that do not exist yet in tool creation and that will be created on next loop in code , that is why you see that line there /null . do not count with support for wsl .
